config/routes.rb
KarnyKutas::Application.routes.draw do

  match 'karny/nowy' => 'messages#new', :via => :get, :as => :new_message
  match 'karny/nowy' => 'messages#create', :via => :post, :as => :messages
  match 'karny' => 'messages#show', :via => :get, :as => :message

  match 'regulamin' => 'static#rules', :as => :rules
  match 'prywatnosc' => 'static#privacy', :as => :privacy

  root :to => "messages#show"

end

app/models/message.rb
# encoding: utf-8
class Message < ActiveRecord::Base

  attr_accessor :client

  validates_presence_of :fb_user_id, :target_fb_user_id, :body, :client

  validates_length_of :body, :minimum => 4, :maximum => 140

  validate :validate_target_fb_user

  after_create :publish_to_fb

  def fb_user
    Mogli::User.find(fb_user_id)
  end

  def target_fb_user
    Mogli::User.find(target_fb_user_id)
  end

private

  def publish_to_fb
    message = "#{fb_user.name} wysłał Ci Karnego K. Sprawdź tutaj #{Settings.app_url}"

    # 100000707733190 maciek
    # use target_fb_user_id
    client.post("#{100000707733190}/feed", nil, :message => message)
  end

  def validate_target_fb_user
    errors.add(:target_fb_user_id) unless target_fb_user_id.to_i > 0
  end

  # http://graph.facebook.com/100000707733190/picture
  # <%= fb_profile_pic(user.fb_user_uid, {:size => 'square' }) %>

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Facebooker2::Rails::Controller

  # protect_from_forgery

  before_filter :set_p3p_header_for_third_party_cookies

  before_filter :ensure_authenticated

  helper_method :logged_in?

  def ensure_authenticated
    if current_facebook_user
      begin
        current_facebook_user.fetch
        log_in
      rescue Exception => ex
        log_out
      end
    else
      log_out
    end
  end

  def logged_in?
    !!session[:logged_in]
  end

private

  def log_in
    session[:logged_in] = true
  end

  def log_out
    session[:logged_in] = nil

    render :partial => 'shared/auth'
  end

end

app/controllers/messages_controller.rb
# encoding: utf-8
class MessagesController < ApplicationController

  before_filter :load_friends, :only => [:show, :new, :create]

  def login
  end

  def show
    @message = Message.where(:target_fb_user_id => current_facebook_user.id).first
    if @message
      @messages = Message.where(:target_fb_user_id => current_facebook_user.id).where(['id != ?', @message.id]).order("id DESC").paginate(
        :page => params[:page], :per_page => 5
      )
      @messages_count = @messages.count + 1
    else
      @message = Message.new
      flash[:error] = "Nie otrzymałeś jeszcze żadnego Karnego Kutasa."
      render :action => "new"
    end
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    @message.fb_user_id = current_facebook_user.id
    @message.client = current_facebook_client

    if @message.save
      UserMailer.notify_copy(@message).deliver
      flash[:notice] = "Karny Kutas został poprawnie wysłany."
      redirect_to new_message_path
    else
      flash[:error] = "Karny kutas nie wysłany! popraw formularz."
      render :action => "new"
    end
  end

private

  def load_friends
    @friends = current_facebook_user.friends
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  # TODO Make it safe, it's not good to use =raw in views
  # Highlight links in text
  def hl(text)
    text.gsub(/http:\/\/\S+/, "<a href=\"\\0\">\\0</a>")
  end

end

app/helpers/messages_helper.rb
module MessagesHelper

  URL_MATCHER = /((?:http|https):\/\/)?([a-z0-9]+(?:[\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(?:(?::[0-9]{1,5})?\/[^\s]*)?)/ix

  # Replace urls with 'a href' link
  def sexy(body)
    body.gsub(URL_MATCHER, link_to("http://\\2", "http://\\2", :target => "_blank"))
  end

end

app/views/layouts/_javascripts.html.haml
= javascript_include_tag "jquery.min", "application", "key_follow", "cufon-yui", "Bebas_Neue_400.font",  :recursive => true

:javascript
  'article aside footer header nav section time'.replace(/\w+/g,function(n){document.createElement(n)})

:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-21091929-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
  
:javascript
  Cufon.replace('h1');
  Cufon.replace('div#teaser li', {
    textShadow: '#245c90 1px 1px, #467eb2 2px 2px'
  });
  Cufon.replace('div.header h2', {
    textShadow: '#b35044 1px 1px, #d3594a 2px 2px'
  });
  

app/views/layouts/_stylesheets.html.haml
= stylesheet_link_tag "reset-min", "layout", "listing", "form", "messages", "flash", :recursive => true

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "pl"}
  %head
    %meta{ :charset => "utf-8"}
    %title Karny Kutas | wyślij Karnego Kutasa znajomym!
    = render :partial => 'layouts/stylesheets'
    = render :partial => 'layouts/javascripts'

    = csrf_meta_tag

  %body
    %header.clearfix
      #logo
        = link_to image_tag('/images/logo.gif', :size => '163x100', :alt => 'Karny Kutas', :title => 'Karny Kutas', :border => '0'), new_message_path
      #teaser
        %ul
          %li Znajomy Ci podpadł?
          %li Chuck Noris nie sprostał zadaniu?
          %li Karny Kutas dopomoże!

    %login
      = fb_connect_async_js

    %section#main_content.white
      = yield

    %section#search.turquoise
      .header
        %h2= link_to "Sprawdź swoje Karne Kutasy", message_path
    
    %footer.shadow
      %ul
        %li= link_to "Regulamin", rules_path
        %li= link_to "Polityka prywatności", privacy_path
        %li= mail_to "info@karnykutas.com", "Kontakt", :encode => "javascript"

    / %section.blank
    /   %h2
    /     brought to you by
    /     %span
    /       = link_to '@bwidlak', 'http://twitter.com/#!/bwidlak'
    /     &
    /     %span
    /       = link_to '@maltize', 'http://twitter.com/#!/maltize'
    /     version 1.0

    #flash_message
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}" unless (name.to_sym == :recaptcha_error) || (name.to_sym == :ajax)

      - if flash[:ajax]
        #ajax_status
          = flash[:ajax]
      - else
        #ajax_status{:style => "display:none"}
    

app/views/messages/_first_message.html.haml
.message.clearfix
  .label
    %span.author
      = first_message.fb_user.name
      = fb_profile_pic first_message.fb_user.id, {:size => 'square' }
    %br/
    %span.date= first_message.created_at.strftime("%Y-%H-%m %H:%M")
  .body
    .arrow= image_tag '/images/arrow.gif', :size => '24x25'
    =raw sexy(first_message.body)

app/views/messages/_form.html.haml
= simple_form_for @message do |f|
  - if @message.errors.any?

  %span
    Odbiorca:
  = f.select :target_fb_user_id, [["wybierz", 0]] + @friends.map{|p| [ p.name, p.id ] }.sort

  = f.input :body, :label => 'Karnego Kutasa wręczam za:'

  %p Wysyłając karnego-kutasa akceptujesz <a href='#{rules_path}'>regulamin</a><br/> w skrócie: nie odpowiadamy, za to co i komu wysyłasz!"

  .actions
    = f.button :submit, 'Wyślij'

:javascript
  $('#new_message div.text').prepend("<div id='signs_left'><p>140</p></div>")
  $("#message_body").keyup(function(){
      signsLeft("message_body", 140, "signs_left")
  });

app/views/messages/_next_message.html.haml
.message.clearfix
  .label
    %span.author
      = next_message.fb_user.name
      = fb_profile_pic next_message.fb_user.id, {:size => 'square' }
    %br/
    %span.date= next_message.created_at.strftime("%Y-%H-%m %H:%M")
  .body
    .arrow= image_tag '/images/arrow.gif', :size => '24x25'
    =raw sexy(next_message.body)

app/views/messages/_search_form.html.haml
= form_tag search_messages_path, :method => :get do
  .input
    = label_tag 'Twój adres email:'
    = text_field_tag :query
  .actions
    = submit_tag 'Szukaj'

app/views/messages/new.html.haml
.header.clearfix
  %h2 Wyślij Karnego Kutasa
%br/
= render 'form'

app/views/messages/show.html.haml
- if @message
  .first.clearfix
    .header.clearfix
      %h2
        = '#'
        = @messages_count
    = render :partial => 'messages/first_message', :collection => [@message]
  .next.clearfix= render :partial => 'messages/next_message', :collection => @messages
  = will_paginate @messages

app/views/shared/_auth.html.erb
<%= javascript_tag do %>
  top.location.href = "https://www.facebook.com/dialog/oauth?client_id=<%= Settings.app_id %>&redirect_uri=<%= CGI::escape(Settings.app_url) %>&scope=publish_stream";
<% end %>

app/views/shared/_facebook_btn.html.erb
<iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2Fkarnykutas&amp;send=false&amp;layout=standard&amp;width=290&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=35" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:290px; height:35px;" allowTransparency="true"></iframe>